<a href="https://colab.research.google.com/github/mdcorva/Ingenias-DataScience/blob/main/Notebook_5_NumPy__Grupo10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
#Importamos primero la libreria y su alias
import numpy as np

In [ ]:
#1.Crear un arreglo de ceros de longitud 12
ceros=np.zeros(12) #Creamos un array compuesto por ceros con la función np.zeros y en el argumento colocamos la longitud (12)
ceros              #Ejecutamos

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#2.Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
ceros=np.zeros(10) #Creamos un array compuesto por ceros con la función np.zeros y en el argumento colocamos la longitud (10)
ceros[5]=10        # Indicamos que en la posición número 5 queremos el valor 10
ceros

array([ 0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.])

In [ ]:
#3.Crear un arreglo que tenga los números del 10 al 49
a=range(10,50) # Definimos una variable y usamos la función range para traer los números entre 10 y 49, tomando como máximo valor 50 para que incluya el 49
a=np.array(a)  # Convertimos esa lista de un array
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
#4.Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
b=range(0,9) # Definimos una variable y usamos la función range para traer los números entre 0 y 8 inclusive
c= np.reshape(b,(3,3)) #Formateamos el array en para que sean 3 filas y 3 columnas (3,3) con la función np.reshape
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#5.Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
arr = np.random.rand(100) # Creamos un arreglo de números aleatorios con 100 números
mean = np.mean(arr)       # Obtenemos la media del arreglo con la función np.mean
var = np.var(arr)         # Obtenemos la varianza del arreglo con la función np.var
print(mean)               #Vemos el resultado
print(var)                #Vemos el resultado

#def aleatorio():
#  #a es la longitud del arreglo
# return(np.random.randn(a))


0.5224846310712395
0.07864450804480932


In [ ]:
#6.Calcular la media de un arreglo usando np.sum

#def media(arreglo):
  #suma=np.sum(arreglo)
  #n=len(arreglo)
  #return(suma/n)

def media(arreglo):                            #Armamos una función para calcular la media donde el parámetro sea el arreglo
  mean = np.sum(arreglo) / len(arreglo)        #Definimos la media diviendo el total del arreglo(np.sum) por la cantidad de registros en el arreglo(len)





In [ ]:
#7.Calcular la varianza de un arreglo usando np.sum y np.mean
#def varianza(arreglo):
#  media=np.mean(arreglo)
#  suma=sum(arreglo-media)
#  n=len(arreglo)
#  return(suma/n)

d=np.random.randint(100,size=100)  #Generamos un arreglo aleatorio de 100 números enteros con la función np.random.randint
media=np.mean(d)                   #Calculamos la media con np.mean
varia=np.var(d)                    #Calculamos la varianza
print(media)                       #Vemos el resultado
print(varia)                       #Vemos el resultado

47.2
805.0


In [ ]:
#8.Crear un array de números aleatorios usando np.random.randn.
y=np.random.rand (5) #Generamos un array con valores al azar con una distribución entre 0 y 1 y segun las dimensiones pasadas como argumento(5)
print(y)             #Vemos el resultado

[0.21915869 0.26836537 0.82444081 0.91037685 0.68506135]
